# Generated by Django 2.1.4 on 2019-04-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100, verbose_name='アーティスト名')),
                ('artist_id', models.IntegerField(default=0, verbose_name='アーティストid')),
                ('concert_date', models.DateField(verbose_name='公演日')),
                ('max_price', models.IntegerField(default=0, verbose_name='価格')),
            ],
        ),
    ]
