# Generated by Django 2.1.4 on 2019-06-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_notify_app', '0003_auto_20190423_0919'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concert',
            table='concert',
        ),
    ]
